// Copyright (c) 2019 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package field

import "github.com/xichen2020/eventdb/values/iterator"
import (
	"errors"

	"github.com/xichen2020/eventdb/document/field"

	"github.com/xichen2020/eventdb/index"
)

var (
	errPositionIterIntIterCountMismatch = errors.New("value iterator and the doc ID position iterator count mismatch")
)

type atPositionIntFieldIterator struct {
	docIDPosIt     index.DocIDPositionIterator
	valsIt         iterator.ForwardIntIterator
	seekableValsIt iterator.SeekableIntIterator
	valAsUnionFn   field.IntAsUnionFn

	done           bool
	err            error
	firstTime      bool
	currPos        int
	currMaskingPos int
	currDocID      int32
	currVal        int
}

func newAtPositionIntFieldIterator(
	docIDPosIt index.DocIDPositionIterator,
	valsIt iterator.ForwardIntIterator,
	valAsUnionFn field.IntAsUnionFn,
) *atPositionIntFieldIterator {
	seekableValsIt, _ := valsIt.(iterator.SeekableIntIterator)
	if seekableValsIt != nil {
		valsIt = nil
	}
	return &atPositionIntFieldIterator{
		docIDPosIt:     docIDPosIt,
		valsIt:         valsIt,
		valAsUnionFn:   valAsUnionFn,
		seekableValsIt: seekableValsIt,
		firstTime:      true,
	}
}

func (it *atPositionIntFieldIterator) Next() bool {
	if it.done || it.err != nil {
		return false
	}
	if !it.docIDPosIt.Next() {
		it.done = true
		return false
	}
	nextPos := it.docIDPosIt.Position()
	distance := nextPos - it.currPos

	// We have a next position, now advance the values iterator for the first time.
	if it.firstTime {
		it.firstTime = false
		if hasNoValues :=
			(it.seekableValsIt != nil && !it.seekableValsIt.Next()) ||
				(it.valsIt != nil && !it.valsIt.Next()); hasNoValues {
			it.err = errPositionIterIntIterCountMismatch
			return false
		}
	}

	if it.seekableValsIt != nil {
		if it.err = it.seekableValsIt.SeekForward(distance); it.err != nil {
			return false
		}
		it.currVal = it.seekableValsIt.Current()
	} else {
		for i := 0; i < distance; i++ {
			if !it.valsIt.Next() {
				it.err = errPositionIterIntIterCountMismatch
				return false
			}
		}
		it.currVal = it.valsIt.Current()
	}

	it.currPos = nextPos
	it.currMaskingPos = it.docIDPosIt.MaskingPosition()
	it.currDocID = it.docIDPosIt.DocID()
	return true
}

func (it *atPositionIntFieldIterator) DocID() int32 { return it.currDocID }

func (it *atPositionIntFieldIterator) Value() int { return it.currVal }

func (it *atPositionIntFieldIterator) ValueUnion() field.ValueUnion {
	return it.valAsUnionFn(it.currVal)
}

func (it *atPositionIntFieldIterator) MaskingPosition() int { return it.currMaskingPos }

func (it *atPositionIntFieldIterator) Err() error { return it.err }

func (it *atPositionIntFieldIterator) Close() {
	it.docIDPosIt.Close()
	it.docIDPosIt = nil
	if it.valsIt != nil {
		it.valsIt.Close()
		it.valsIt = nil
	} else {
		it.seekableValsIt.Close()
		it.seekableValsIt = nil
	}
	it.err = nil
}
