// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package field

import "github.com/xichen2020/eventdb/values/iterator"
import (
	"github.com/xichen2020/eventdb/document/field"

	"github.com/xichen2020/eventdb/index"

	xerrors "github.com/m3db/m3x/errors"
)

type stringFieldIterator struct {
	docIt        index.DocIDSetIterator
	valIt        iterator.ForwardStringIterator
	valAsUnionFn field.StringAsUnionFn

	done      bool
	err       error
	currDocID int32
	currValue string
}

func newStringFieldIterator(
	docIt index.DocIDSetIterator,
	valIt iterator.ForwardStringIterator,
	valAsUnionFn field.StringAsUnionFn,
) *stringFieldIterator {
	return &stringFieldIterator{
		docIt:        docIt,
		valIt:        valIt,
		valAsUnionFn: valAsUnionFn,
	}
}

func (it *stringFieldIterator) Next() bool {
	if it.done || it.err != nil {
		return false
	}
	if !it.docIt.Next() || !it.valIt.Next() {
		it.done = true
		// TODO(xichen): Add doc it errors as well.
		var multiErr xerrors.MultiError
		if err := it.valIt.Err(); err != nil {
			multiErr = multiErr.Add(err)
		}
		it.err = multiErr.FinalError()
		return false
	}
	it.currDocID = it.docIt.DocID()
	it.currValue = it.valIt.Current()
	return true
}

func (it *stringFieldIterator) DocID() int32 { return it.currDocID }

func (it *stringFieldIterator) Value() string { return it.currValue }

func (it *stringFieldIterator) ValueUnion() field.ValueUnion {
	// NB(xichen): This should be inlined.
	return it.valAsUnionFn(it.currValue)
}

func (it *stringFieldIterator) Err() error { return it.err }

func (it *stringFieldIterator) Close() {
	it.docIt.Close()
	it.docIt = nil
	it.valIt.Close()
	it.valIt = nil
	it.err = nil
}
