// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package proto

import (
	"encoding/binary"

	"io"

	"github.com/xichen2020/eventdb/generated/proto/encodingpb"
	"github.com/xichen2020/eventdb/x/bytes"
)

// *encodingpb.StringLengths is a generic gogo protobuf generated Message type.

// EncodeStringLengths encodes a GenericValue message into a `io.Writer`.
// pool if the array is at capacity.
func EncodeStringLengths(
	msg *encodingpb.StringLengths,
	extBuf *[]byte, // extBuf is an external byte buffer for memory re-use.
	writer io.Writer,
) error {
	protoSizeBytes := msg.Size()
	*extBuf = bytes.EnsureBufferSize(*extBuf, protoSizeBytes, bytes.DontCopyData)
	n := binary.PutVarint(*extBuf, int64(protoSizeBytes))
	if _, err := writer.Write((*extBuf)[:n]); err != nil {
		return err
	}
	if _, err := msg.MarshalTo((*extBuf)[:protoSizeBytes]); err != nil {
		return err
	}
	_, err := writer.Write((*extBuf)[:protoSizeBytes])
	return err
}
