// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package pool

import (
	"github.com/m3db/m3x/instrument"
)

// BytesArrayBucketConfiguration contains configuration for a pool bucket.
type BytesArrayBucketConfiguration struct {
	// The count of the items in the bucket.
	Count int `yaml:"count"`

	// The capacity of each item in the bucket.
	Capacity int `yaml:"capacity"`
}

// NewBucket creates a new bucket.
func (c *BytesArrayBucketConfiguration) NewBucket() BytesArrayBucket {
	return BytesArrayBucket{
		Capacity: c.Capacity,
		Count:    c.Count,
	}
}

// BucketizedBytesArrayPoolConfiguration contains configuration for bucketized pools.
type BucketizedBytesArrayPoolConfiguration struct {
	// The pool bucket configuration.
	Buckets []BytesArrayBucketConfiguration `yaml:"buckets"`

	// The watermark configuration.
	Watermark BytesArrayPoolWatermarkConfiguration `yaml:"watermark"`
}

// NewPoolOptions creates a new set of pool options.
func (c *BucketizedBytesArrayPoolConfiguration) NewPoolOptions(
	instrumentOptions instrument.Options,
) *BytesArrayPoolOptions {
	return NewBytesArrayPoolOptions().
		SetInstrumentOptions(instrumentOptions).
		SetRefillLowWatermark(c.Watermark.RefillLowWatermark).
		SetRefillHighWatermark(c.Watermark.RefillHighWatermark)
}

// NewBuckets create a new list of buckets.
func (c *BucketizedBytesArrayPoolConfiguration) NewBuckets() []BytesArrayBucket {
	buckets := make([]BytesArrayBucket, 0, len(c.Buckets))
	for _, bconfig := range c.Buckets {
		bucket := bconfig.NewBucket()
		buckets = append(buckets, bucket)
	}
	return buckets
}
