// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package pool

import (
	"fmt"

	"sort"

	"github.com/uber-go/tally"
)

// StringArrayBucket specifies a bucket.
type StringArrayBucket struct {
	// Capacity is the size of each element in the bucket.
	Capacity int

	// Count is the number of fixed elements in the bucket.
	Count int

	// Options is an optional override to specify options to use for a bucket,
	// specify nil to use the options specified to the bucketized pool
	// constructor for this bucket.
	Options *StringArrayPoolOptions
}

// stringArrayBucketByCapacity is a sortable collection of pool buckets.
type stringArrayBucketByCapacity []StringArrayBucket

func (x stringArrayBucketByCapacity) Len() int {
	return len(x)
}

func (x stringArrayBucketByCapacity) Swap(i, j int) {
	x[i], x[j] = x[j], x[i]
}

func (x stringArrayBucketByCapacity) Less(i, j int) bool {
	return x[i].Capacity < x[j].Capacity
}

type stringArrayBucketPool struct {
	capacity int
	pool     *StringArrayPool
}

// BucketizedStringArrayPool is a bucketized value pool.
type BucketizedStringArrayPool struct {
	sizesAsc          []StringArrayBucket
	buckets           []stringArrayBucketPool
	maxBucketCapacity int
	opts              *StringArrayPoolOptions
	alloc             func(capacity int) []string
	maxAlloc          tally.Counter
}

// NewBucketizedStringArrayPool creates a bucketized object pool.
func NewBucketizedStringArrayPool(sizes []StringArrayBucket, opts *StringArrayPoolOptions) *BucketizedStringArrayPool {
	if opts == nil {
		opts = NewStringArrayPoolOptions()
	}

	sizesAsc := make([]StringArrayBucket, len(sizes))
	copy(sizesAsc, sizes)
	sort.Sort(stringArrayBucketByCapacity(sizesAsc))

	var maxBucketCapacity int
	if len(sizesAsc) != 0 {
		maxBucketCapacity = sizesAsc[len(sizesAsc)-1].Capacity
	}

	return &BucketizedStringArrayPool{
		opts:              opts,
		sizesAsc:          sizesAsc,
		maxBucketCapacity: maxBucketCapacity,
		maxAlloc:          opts.InstrumentOptions().MetricsScope().Counter("alloc-max"),
	}
}

// Init initializes the bucketized pool.
func (p *BucketizedStringArrayPool) Init(alloc func(capacity int) []string) {
	buckets := make([]stringArrayBucketPool, len(p.sizesAsc))
	for i := range p.sizesAsc {
		size := p.sizesAsc[i].Count
		capacity := p.sizesAsc[i].Capacity

		opts := p.opts
		if perBucketOpts := p.sizesAsc[i].Options; perBucketOpts != nil {
			opts = perBucketOpts
		}

		opts = opts.SetSize(size)
		scope := opts.InstrumentOptions().MetricsScope()
		iOpts := opts.InstrumentOptions().
			SetMetricsScope(scope.Tagged(map[string]string{
				"bucket-capacity": fmt.Sprintf("%d", capacity),
			}))
		opts.SetInstrumentOptions(iOpts)

		buckets[i].capacity = capacity
		buckets[i].pool = NewStringArrayPool(opts)
		buckets[i].pool.Init(func() []string {
			return alloc(capacity)
		})
	}
	p.buckets = buckets
	p.alloc = alloc
}

// Get gets a value from the pool.
func (p *BucketizedStringArrayPool) Get(capacity int) []string {
	if capacity > p.maxBucketCapacity {
		p.maxAlloc.Inc(1)
		return p.alloc(capacity)
	}
	for i := range p.buckets {
		if p.buckets[i].capacity >= capacity {
			return p.buckets[i].pool.Get()
		}
	}
	return p.alloc(capacity)
}

// Put puts a value to the pool.
func (p *BucketizedStringArrayPool) Put(v []string, capacity int) {
	if capacity > p.maxBucketCapacity {
		return
	}

	for i := len(p.buckets) - 1; i >= 0; i-- {
		if capacity >= p.buckets[i].capacity {
			p.buckets[i].pool.Put(v)
			return
		}
	}
}
