// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package pool

import (
	"github.com/xichen2020/eventdb/x/refcnt"
)

// *BucketizedInt64ArrayPool is a generic bucketized value array pool.

// RefCountedPooledInt64Array is a refcounted, pooled generic value array.
type RefCountedPooledInt64Array struct {
	closed bool
	cnt    *refcnt.RefCounter
	p      *BucketizedInt64ArrayPool
	vals   []int64
}

// NewRefCountedPooledInt64Array creates a new refcounted, pooled generic value array.
func NewRefCountedPooledInt64Array(
	vals []int64,
	p *BucketizedInt64ArrayPool,
) *RefCountedPooledInt64Array {
	return &RefCountedPooledInt64Array{
		cnt:  refcnt.NewRefCounter(),
		p:    p,
		vals: vals,
	}
}

// Get returns the underlying raw value array.
func (rv *RefCountedPooledInt64Array) Get() []int64 { return rv.vals }

// Snapshot takes a snapshot of the current values in the refcounted array.
// The returned snapshot shares the backing array with the source array but
// keeps a copy of the array slice as the snapshot. As a result, new values
// appended to the end of the array after the snapshot is taken is invisible
// to the snapshot.
func (rv *RefCountedPooledInt64Array) Snapshot() *RefCountedPooledInt64Array {
	rv.cnt.IncRef()
	return &RefCountedPooledInt64Array{
		cnt:  rv.cnt,
		p:    rv.p,
		vals: rv.vals,
	}
}

// Append appends a value to the value array.
func (rv *RefCountedPooledInt64Array) Append(v int64) {
	if len(rv.vals) < cap(rv.vals) {
		rv.vals = append(rv.vals, v)
		return
	}
	newVals := rv.p.Get(cap(rv.vals) * 2)
	n := copy(newVals[:len(rv.vals)], rv.vals)
	newVals = newVals[:n]
	newVals = append(newVals, v)
	rv.tryRelease()
	rv.cnt = refcnt.NewRefCounter()
	rv.vals = newVals
}

// Close closes the ref counted array.
func (rv *RefCountedPooledInt64Array) Close() {
	if rv.closed {
		return
	}
	rv.closed = true
	rv.tryRelease()
}

func (rv *RefCountedPooledInt64Array) tryRelease() {
	if rv.cnt.DecRef() > 0 {
		return
	}
	rv.vals = rv.vals[:0]
	rv.p.Put(rv.vals, cap(rv.vals))
	rv.vals = nil
	rv.cnt = nil
}
