logging:
    level: info

metrics:
  scope:
    reportingInterval: 1s
  m3:
    hostPort: 127.0.0.1:1234
    service: eventdb
    tags:
      instance: 0
    env: production
    includeHost: true
  samplingRate: 0.01
  extended: moderate

grpc:
  listenAddress: 0.0.0.0:5678
  readBufferSize: 1048576 # 1MB
  maxRecvMsgSize: 67108864 # 64MB
  keepAlivePeriod: 10m
  service:
    readTimeout: 1m
    writeTimeout: 1m
    documentArrayPool:
      buckets:
        - count: 16
          capacity: 1024
        - count: 16
          capacity: 2048
        - count: 16
          capacity: 4096
        - count: 16
          capacity: 8192
        - count: 16
          capacity: 16384
        - count: 16
          capacity: 32768
      watermark:
        low: 0.7
        high: 1.0
    fieldArrayPool:
      buckets:
        - count: 8192
          capacity: 64
        - count: 8192
          capacity: 128
        - count: 4096
          capacity: 256
        - count: 2048
          capacity: 512
        - count: 1024
          capacity: 1024
      watermark:
        low: 0.7
        high: 1.0

http:
  listenAddress: 0.0.0.0:5679
  service:
    readTimeout: 1m
    writeTimeout: 1m
    parserPool:
      size: 50000
      watermark:
        low: 0.001
        high: 0.002
    parser:
      maxDepth: 3
      excludeKeySuffix: _noindex

database:
  namespaces:
    - id: testNamespace
  numShards: 8
  filePathPrefix: /var/lib/eventdb
  fieldPathSeparator: .
  namespaceFieldName: service
  timestampFieldName: "@timestamp"
  tickMinInterval: 1m
  maxNumDocsPerSegment: 1048576
  segmentUnloadAfterUnreadFor: 5m
  persist:
    writeBufferSize: 65536
    readBufferSize: 65536
    timestampPrecision: 1ms
    mmapEnableHugePages: true
    mmapHugePagesThreshold: 16384 # 2 ^ 14
  boolArrayPool: # total < 1GB
    buckets:
      - count: 5000
        capacity: 4096
      - count: 5000
        capacity: 8192
      - count: 5000
        capacity: 16384
      - count: 5000
        capacity: 32768
      - count: 5000
        capacity: 65536
    watermark:
      low: 0.7
      high: 1.0
  intArrayPool: # total < 1GB
    buckets:
      - count: 1000
        capacity: 4096
      - count: 1000
        capacity: 8192
      - count: 1000
        capacity: 16384
      - count: 1000
        capacity: 32768
      - count: 1000
        capacity: 65536
    watermark:
      low: 0.7
      high: 1.0
  int64ArrayPool: # For timestamps, 8 shards * 2 segments = 16, ~250MB
    buckets:
      - count: 32
        capacity: 65536
      - count: 32
        capacity: 131072
      - count: 32
        capacity: 262144
      - count: 32
        capacity: 524288
    watermark:
      low: 0.001
      high: 0.002
  doubleArrayPool: # total < 1GB
    buckets:
      - count: 1000
        capacity: 4096
      - count: 1000
        capacity: 8192
      - count: 1000
        capacity: 16384
      - count: 1000
        capacity: 32768
      - count: 1000
        capacity: 65536
    watermark:
      low: 0.7
      high: 1.0
  stringArrayPool: # 1K string fields * 8 shards * 2 segments = 16K, ~15G
    buckets:
      - count: 1600
        capacity: 8192
      - count: 1600
        capacity: 16384
      - count: 1600
        capacity: 32768
      - count: 1600
        capacity: 65536
      - count: 1600
        capacity: 131072
      - count: 1600
        capacity: 262144
      - count: 1600
        capacity: 524288
    watermark:
      low: 0.7
      high: 1.0
