// Copyright (c) 2019 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package decoding

import (
	"io"

	xio "github.com/xichen2020/eventdb/x/io"

	bitstream "github.com/dgryski/go-bitstream"
)

type applyOpToIntIntFn func(v int, delta int) int

// deltaIntIterator iterates over a stream of delta encoded data.
type deltaIntIterator struct {
	bitReader           *bitstream.BitReader
	bitsPerEncodedValue int64
	addFn               applyOpToIntIntFn
	negativeBit         uint64

	closed       bool
	curr         int
	err          error
	isDeltaValue bool
}

func newDeltaIntIterator(
	reader xio.Reader,
	bitsPerEncodedValue int64, // This includes the sign bit
	addFn applyOpToIntIntFn,
) *deltaIntIterator {
	return &deltaIntIterator{
		bitReader:           bitstream.NewReader(reader),
		bitsPerEncodedValue: bitsPerEncodedValue,
		addFn:               addFn,
		negativeBit:         1 << uint(bitsPerEncodedValue-1),
	}
}

// Next returns true if there are more values to be iterated over.
func (it *deltaIntIterator) Next() bool {
	if it.closed || it.err != nil {
		return false
	}

	// First value is special and written as 64 bits.
	if !it.isDeltaValue {
		var firstValue uint64
		// The first value is encoded in full 64 bit.
		firstValue, it.err = it.bitReader.ReadBits(64)
		if it.err != nil {
			return false
		}
		it.curr = int(firstValue)
		// The remaining values are delta values.
		it.isDeltaValue = true
		return true
	}

	// Read in an extra bit for the sign.
	var delta uint64
	delta, it.err = it.bitReader.ReadBits(int(it.bitsPerEncodedValue))
	if it.err != nil {
		return false
	}
	// Check if negative bit is set.
	intDelta := int(delta)
	isNegative := (delta & it.negativeBit) == it.negativeBit
	if isNegative {
		// Zero out the negative bit.
		delta &^= it.negativeBit
		intDelta = -int(delta)
	}
	it.curr = it.addFn(it.curr, intDelta)
	return true
}

// Current returns the current int.
func (it *deltaIntIterator) Current() int { return it.curr }

// Err returns any error recorded while iterating.
// NB(xichen): This ignores `io.EOF`.
func (it *deltaIntIterator) Err() error {
	if it.err == io.EOF {
		return nil
	}
	return it.err
}

// Close closes the iterator.
func (it *deltaIntIterator) Close() error {
	if it.closed {
		return nil
	}
	it.closed = true
	it.bitReader = nil
	it.err = nil
	it.addFn = nil
	return nil
}
