// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package impl

import "github.com/xichen2020/eventdb/values/iterator"
import "github.com/xichen2020/eventdb/filter"

// FilteredDoubleIterator is a position iterator that outputs the positions
// of values in the value sequence matching a given filter. The position starts at 0.
type FilteredDoubleIterator struct {
	vit iterator.ForwardDoubleIterator
	f   filter.DoubleFilter

	done    bool
	currPos int
	err     error
}

// NewFilteredDoubleIterator creates a new filtering iterator.
func NewFilteredDoubleIterator(
	vit iterator.ForwardDoubleIterator,
	f filter.DoubleFilter,
) *FilteredDoubleIterator {
	return &FilteredDoubleIterator{
		vit:     vit,
		f:       f,
		currPos: -1,
	}
}

// Next returns true if there are more values to be iterated over.
func (it *FilteredDoubleIterator) Next() bool {
	if it.done || it.err != nil {
		return false
	}
	for it.vit.Next() {
		it.currPos++
		if it.f.Match(it.vit.Current()) {
			return true
		}
	}
	it.done = true
	it.err = it.vit.Err()
	return false
}

// Position returns the current position.
func (it *FilteredDoubleIterator) Position() int { return it.currPos }

// Err returns any errors encountered during iteration.
func (it *FilteredDoubleIterator) Err() error { return it.err }

// Close closes the iterator.
func (it *FilteredDoubleIterator) Close() {
	it.vit.Close()
	it.vit = nil
	it.f = nil
}
