// Copyright (c) 2019 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/xichen2020/eventdb/values/iterator (interfaces: ForwardBoolIterator,ForwardIntIterator,ForwardDoubleIterator,ForwardStringIterator,ForwardTimeIterator)

package iterator

import (
	"github.com/golang/mock/gomock"
)

// Mock of ForwardBoolIterator interface
type MockForwardBoolIterator struct {
	ctrl     *gomock.Controller
	recorder *_MockForwardBoolIteratorRecorder
}

// Recorder for MockForwardBoolIterator (not exported)
type _MockForwardBoolIteratorRecorder struct {
	mock *MockForwardBoolIterator
}

func NewMockForwardBoolIterator(ctrl *gomock.Controller) *MockForwardBoolIterator {
	mock := &MockForwardBoolIterator{ctrl: ctrl}
	mock.recorder = &_MockForwardBoolIteratorRecorder{mock}
	return mock
}

func (_m *MockForwardBoolIterator) EXPECT() *_MockForwardBoolIteratorRecorder {
	return _m.recorder
}

func (_m *MockForwardBoolIterator) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardBoolIteratorRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockForwardBoolIterator) Current() bool {
	ret := _m.ctrl.Call(_m, "Current")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockForwardBoolIteratorRecorder) Current() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Current")
}

func (_m *MockForwardBoolIterator) Err() error {
	ret := _m.ctrl.Call(_m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardBoolIteratorRecorder) Err() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Err")
}

func (_m *MockForwardBoolIterator) Next() bool {
	ret := _m.ctrl.Call(_m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockForwardBoolIteratorRecorder) Next() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Next")
}

// Mock of ForwardIntIterator interface
type MockForwardIntIterator struct {
	ctrl     *gomock.Controller
	recorder *_MockForwardIntIteratorRecorder
}

// Recorder for MockForwardIntIterator (not exported)
type _MockForwardIntIteratorRecorder struct {
	mock *MockForwardIntIterator
}

func NewMockForwardIntIterator(ctrl *gomock.Controller) *MockForwardIntIterator {
	mock := &MockForwardIntIterator{ctrl: ctrl}
	mock.recorder = &_MockForwardIntIteratorRecorder{mock}
	return mock
}

func (_m *MockForwardIntIterator) EXPECT() *_MockForwardIntIteratorRecorder {
	return _m.recorder
}

func (_m *MockForwardIntIterator) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardIntIteratorRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockForwardIntIterator) Current() int {
	ret := _m.ctrl.Call(_m, "Current")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockForwardIntIteratorRecorder) Current() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Current")
}

func (_m *MockForwardIntIterator) Err() error {
	ret := _m.ctrl.Call(_m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardIntIteratorRecorder) Err() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Err")
}

func (_m *MockForwardIntIterator) Next() bool {
	ret := _m.ctrl.Call(_m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockForwardIntIteratorRecorder) Next() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Next")
}

// Mock of ForwardDoubleIterator interface
type MockForwardDoubleIterator struct {
	ctrl     *gomock.Controller
	recorder *_MockForwardDoubleIteratorRecorder
}

// Recorder for MockForwardDoubleIterator (not exported)
type _MockForwardDoubleIteratorRecorder struct {
	mock *MockForwardDoubleIterator
}

func NewMockForwardDoubleIterator(ctrl *gomock.Controller) *MockForwardDoubleIterator {
	mock := &MockForwardDoubleIterator{ctrl: ctrl}
	mock.recorder = &_MockForwardDoubleIteratorRecorder{mock}
	return mock
}

func (_m *MockForwardDoubleIterator) EXPECT() *_MockForwardDoubleIteratorRecorder {
	return _m.recorder
}

func (_m *MockForwardDoubleIterator) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardDoubleIteratorRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockForwardDoubleIterator) Current() float64 {
	ret := _m.ctrl.Call(_m, "Current")
	ret0, _ := ret[0].(float64)
	return ret0
}

func (_mr *_MockForwardDoubleIteratorRecorder) Current() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Current")
}

func (_m *MockForwardDoubleIterator) Err() error {
	ret := _m.ctrl.Call(_m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardDoubleIteratorRecorder) Err() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Err")
}

func (_m *MockForwardDoubleIterator) Next() bool {
	ret := _m.ctrl.Call(_m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockForwardDoubleIteratorRecorder) Next() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Next")
}

// Mock of ForwardStringIterator interface
type MockForwardStringIterator struct {
	ctrl     *gomock.Controller
	recorder *_MockForwardStringIteratorRecorder
}

// Recorder for MockForwardStringIterator (not exported)
type _MockForwardStringIteratorRecorder struct {
	mock *MockForwardStringIterator
}

func NewMockForwardStringIterator(ctrl *gomock.Controller) *MockForwardStringIterator {
	mock := &MockForwardStringIterator{ctrl: ctrl}
	mock.recorder = &_MockForwardStringIteratorRecorder{mock}
	return mock
}

func (_m *MockForwardStringIterator) EXPECT() *_MockForwardStringIteratorRecorder {
	return _m.recorder
}

func (_m *MockForwardStringIterator) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardStringIteratorRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockForwardStringIterator) Current() string {
	ret := _m.ctrl.Call(_m, "Current")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockForwardStringIteratorRecorder) Current() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Current")
}

func (_m *MockForwardStringIterator) Err() error {
	ret := _m.ctrl.Call(_m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardStringIteratorRecorder) Err() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Err")
}

func (_m *MockForwardStringIterator) Next() bool {
	ret := _m.ctrl.Call(_m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockForwardStringIteratorRecorder) Next() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Next")
}

// Mock of ForwardTimeIterator interface
type MockForwardTimeIterator struct {
	ctrl     *gomock.Controller
	recorder *_MockForwardTimeIteratorRecorder
}

// Recorder for MockForwardTimeIterator (not exported)
type _MockForwardTimeIteratorRecorder struct {
	mock *MockForwardTimeIterator
}

func NewMockForwardTimeIterator(ctrl *gomock.Controller) *MockForwardTimeIterator {
	mock := &MockForwardTimeIterator{ctrl: ctrl}
	mock.recorder = &_MockForwardTimeIteratorRecorder{mock}
	return mock
}

func (_m *MockForwardTimeIterator) EXPECT() *_MockForwardTimeIteratorRecorder {
	return _m.recorder
}

func (_m *MockForwardTimeIterator) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardTimeIteratorRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockForwardTimeIterator) Current() int64 {
	ret := _m.ctrl.Call(_m, "Current")
	ret0, _ := ret[0].(int64)
	return ret0
}

func (_mr *_MockForwardTimeIteratorRecorder) Current() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Current")
}

func (_m *MockForwardTimeIterator) Err() error {
	ret := _m.ctrl.Call(_m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockForwardTimeIteratorRecorder) Err() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Err")
}

func (_m *MockForwardTimeIterator) Next() bool {
	ret := _m.ctrl.Call(_m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockForwardTimeIteratorRecorder) Next() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Next")
}
